src/v2/examples/commits.md, src/v2/examples/elastic-header.md, src/v2/examples/firebase.md, src/v2/examples/grid-component.md, src/v2/examples/hackernews.md, src/v2/examples/index.md, src/v2/examples/modal.md, src/v2/examples/select2.md, src/v2/examples/svg.md, src/v2/examples/todomvc.md, src/v2/examples/tree-view.md
Hey guys! Please add some comments to improve this translations
=> Initial translation for Examples page

src/v2/guide/conditional.md
Управление повторным использованием элементов при помощи `key` - отсутствуют уникальные ключи во втором примере
=> Управление повторным использованием элементов

themes/vue/layout/layout.ejs, themes/vue/source/js/common.js, themes/vue/source/js/css.escape.js
Решение одной из двух проблем связанных с https://github.com/translation-gang/ru.vuejs.org/issues/66
Исправлено в оригинальном репо в https://github.com/vuejs/vuejs.org/pull/709 и  https://github.com/vuejs/vuejs.org/pull/711
=> - Исправление меняющегося хэша при наличии не ASCII-символов

src/v2/guide/render-function.md
Clarify compilation sample in section of render function
Its correspondence to vuejs/vuejs.org#749
=> Update compilation sample

src/v2/guide/custom-directive.md
https://github.com/vuejs/vuejs.org/pull/764
=> Исправлен пример с custom-directive

themes/vue/layout/index.ejs, themes/vue/layout/layout.ejs, themes/vue/layout/partials/ad.ejs, themes/vue/layout/partials/header.ejs, themes/vue/layout/partials/main_menu.ejs, themes/vue/layout/partials/sidebar.ejs, themes/vue/layout/partials/sponsors.ejs, themes/vue/layout/post.ejs, themes/vue/source/css/_header.styl
https://github.com/vuejs/vuejs.org/pull/774
=> - Fixed hero structure

src/v2/api/index.md
Когда смержат https://github.com/vuejs/vuejs.org/pull/794
=> api.md добавлены варианты типов параметров

src/v2/guide/components.md, src/v2/guide/list.md
- https://github.com/vuejs/vuejs.org/pull/797
- https://github.com/vuejs/vuejs.org/pull/799
=> Исправление пары примеров

src/v2/guide/render-function.md
См. https://github.com/vuejs/vuejs.org/commit/8912ec69ca98354237479e0dde31056688b579f2
=> render-function.md: замена кавычек в примере

src/v2/guide/render-function.md
См. https://github.com/vuejs/vuejs.org/pull/1419
=> render-function.md: обновление

themes/vue/source/css/_header.styl
См. https://github.com/vuejs/vuejs.org/commit/38f492e6ff0deb194df98a3d0180da73b0f43ed4
=> _header.styl: обновление

src/v2/cookbook/form-validation.md
См. https://github.com/vuejs/vuejs.org/commit/42d047b309fe1fd1a652a4be8ff0e0cd8c2aec8c
=> form-validation.md: обновление

src/v2/style-guide/index.md
См. https://github.com/vuejs/vuejs.org/commit/9930eabde06910a885146247ce32854e5517ade5
=> style-guide: добавление заголовка страницы

themes/vue/source/css/_common.styl, themes/vue/source/css/_demo.styl, themes/vue/source/css/page.styl
См. https://github.com/vuejs/vuejs.org/commit/44c8fcbb2e10a7f86262dfd27e668476f8b7dd8c
А также патч к нему - https://github.com/vuejs/vuejs.org/commit/addc947eac4b8f915332893172aa566f07dcb7c5
=> Улучшение типографики для печати

src/v2/cookbook/editable-svg-icons.md, src/v2/cookbook/unit-testing-vue-components.md
См. https://github.com/vuejs/vuejs.org/commit/3bce1a3bf780f11efd88774945b80d59cccc5e44
=> Исправления в Cookbook

src/v2/cookbook/serverless-blog.md
См. https://github.com/vuejs/vuejs.org/commit/ec5368015cdae62c7c350b5c74efdea851235cd6
=> Adding serverless blog example (#1457)

themes/vue/source/css/page.styl
См. https://github.com/vuejs/vuejs.org/commit/d31987a26213bb47f29e689cfecadf004b70ae50
=> tweak header link (#1472)

src/v2/guide/installation.md
https://github.com/vuejs/vuejs.org/commit/15bdf0d8cb0cfc05ddc13ccfa8a196fdc9fdea4e
=> installation.md: обновление

themes/vue/layout/partials/ecosystem_dropdown.ejs
https://github.com/vuejs/vuejs.org/commit/49e7acea1653635341109d24c30792c7a5c6dfef
=> ecosystem_dropdown.ejs: обновление

themes/vue/layout/page.ejs
https://github.com/vuejs/vuejs.org/commit/c1d5ce22253ae57c1b7b4736d375819bdb682346
=> page.ejs: обновление

src/v2/cookbook/using-axios-to-consume-apis.md
https://github.com/vuejs/vuejs.org/commit/c3c59496ab63c0d1f680be8e19aeb6aecc8d2f9a
=> using-axios-to-consume-apis.md: новый файл

src/v2/guide/team.md
https://github.com/vuejs/vuejs.org/commit/377d90ee41673fa652808f39ce68c00f4dee8f4c
=> team.md: обновление

src/v2/cookbook/unit-testing-vue-components.md
https://github.com/vuejs/vuejs.org/commit/fc18488df6d6f22b5884f1a52ac0569e77c75b57
=> unit-testing-vue-components.md: обновление

src/v2/guide/render-function.md
В html будет исправлено.
https://github.com/translation-gang/ru.vuejs.org/issues/345
=> Fix menu link

themes/vue/source/js/common.js
https://github.com/translation-gang/ru.vuejs.org/issues/345 https://github.com/translation-gang/ru.vuejs.org/issues/335
В итоге скопировал решение из главного репо :/
=> Fix menu links

themes/vue/layout/partials/ad.ejs
https://github.com/vuejs/vuejs.org/commit/ef9b64e753afb133946d2d6bee774ddff05af74c
=> Обновление кода для рекламы

themes/vue/layout/partials/ecosystem_dropdown.ejs
См. https://github.com/vuejs/vuejs.org/commit/912d564e694995524e6f66aa60ac2a66860a3fe4
=> ecosystem_dropdown: add link for meetups

src/v2/guide/team.md
See https://github.com/vuejs/vuejs.org/commit/918f0e527ad0661f9fadbcc769302b64b4550176
=> team: update

themes/vue/layout/sponsors-page.ejs
Обновление в соответствии с https://github.com/vuejs/vuejs.org/commit/a71f12b323f2a8c85b29a7531eedcfa1879f0ed3
=> sponsors-page.ejs: обновление

src/v2/cookbook/unit-testing-vue-components.md
См. https://github.com/vuejs/vuejs.org/commit/28ef76231cc51cf24bb56a089c0488ad9069a9a5
=> Обновление unit-testing-vue-components.md

src/v2/guide/class-and-style.md, src/v2/guide/components-props.md
according to https://github.com/vuejs/vuejs.org/pull/1895/commits/0d93a3b1145202be4cb46d904a7f09321d08ea49
=> One more format patch

src/v2/guide/class-and-style.md
according to https://github.com/vuejs/vuejs.org/pull/1894/commits/ffab7b834b220b8c59a85609cb4a7bda64fa4b39
=> Unify examples HTML formatting

src/v2/guide/single-file-components.md
Нашел не точность в протоколе ссылки
=> Исправление протокола ссылки

src/v2/guide/unit-testing.md
https://github.com/vuejs/vuejs.org/commit/79f3ee198ffcf6ce199cfcbb2b10945d108d6313
=> Обновление unit-testing.md

README.md
=> README: добавление ссылки на оригинальный репозиторий

src/v2/guide/installation.md
См. https://github.com/vuejs/vuejs.org/commit/aa8b3923f50905127aae42703550b1e686633251
=> installation: обновление

README.md
В соответствии с https://github.com/vuejs/vuejs.org/commit/42c313c8fd0ae84db48fc1287b9d22903d04df67
=> README: обновление

src/v2/guide/components-slots.md
Это единственное, что я нашёл, всё в основном - круто!
=> components-slots.md: правка

themes/vue/layout/partials/ecosystem_dropdown.ejs
В соответствие с https://github.com/vuejs/vuejs.org/commit/bf9b4e96f4c750623641229aedd23464658a52b1
=> cosystem_dropdown.ejs: обновление

themes/vue/source/css/_modal.styl
См. https://github.com/vuejs/vuejs.org/commit/577192b65b37311891957f041bb797acd98aba0a
=> _modal.styl: обновление

src/v2/guide/components-props.md
См. https://github.com/vuejs/vuejs.org/commit/ce208ae4acbbfafe5f2c5904d1fd378b4c883882
=> components-props.md: обновление

themes/vue/source/css/page.styl
В соответствии с https://github.com/vuejs/vuejs.org/commit/852056aa07946899a08ea667ce637c7c436a123a
=> page.styl: обновление

src/v2/cookbook/unit-testing-vue-components.md
Заменил свойство name='Привет' на свойство name='Hello'
=> Исправил ошибку локализации

themes/vue/layout/page.ejs
Немного изменил текст в футере, мне кажется такой вариант логичнее выглядит:
`Обнаружили ошибку или хотите добавить что-то своё в документацию? Измените эту страницу на GitHub!`
Чем такой:
`Обнаружили ошибку или хотите добавить что-то своё в документацию? Изменить эту страницу на GitHub!`
=> Update page layout
